### ISSUE TITLE
Scan Support

### ISSUE THREAD

**Issue by antonymorrish** [Michael-radleysystems/TextMessage#1]
push OnBarcode(szBarcodeData) into the beforepress so script works for both keys and scans

**Comment by antonymorrish** [comment]
`
/**********************************************************************
OnBarcode(szBarcodeData)
Occurs when Barcode scanned but before pos executes bar code.
Return false to stop barcode. true to continue.
**********************************************************************/

function OnBarcode(szBarcodeData)
{
    // Was scanned thing a plu in our program ?
    local nScannedPLU = ICR_GetPLURecNumber(szBarcodeData);
    if((nScannedPLU == null) || (nScannedPLU == 0 ))return true; // Nope. Let till deal with it.
    // If its a plu. do the before press checking we do on the Key.
    if(bDebugPrinting)print("Invoking BKP for BarcodePlu "+nScannedPLU);
    return BeforeKeyPress(1, nScannedPLU, 1000);
}
`

**Comment by Michael-radleysystems** [comment]
Hi Antony I merged the branch antonymorrish-patch-1 in to the TextMessage-master
